import Head from "next/head";

import Layout from "@/component/Layout";
import Navbar from "@/component/Navbar";
import Slider from "@/component/Slider";
import Footer from "@/component/Footer";
import Banner from "@/component/Banner";
import AllProducts from "@/component/AllProducts";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />

          <link
            rel="stylesheet"
            type="text/css"
            charSet="UTF-8"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
          />
          <link
            rel="stylesheet"
            type="text/css"
            href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container">
          <Banner />
          <AllProducts />
        </main>
      </Layout>
      <ToastContainer />
    </>
  );
}
